### ISSUE TITLE
Add twitter feed to website

### ISSUE THREAD

**Issue by brianisbrilliant** [devict/ictgamejam#32]
During the event I imagine that people will look to our website for directions or theme or other information. Instead of updating the website A LOT with that information - what if we just had a Twitter widget and updated that?

**Comment by catcecilia** [comment]
Hi there! I saw that there was a hacktober event and wanted to share some input.  

I think if you want to go this route, you have to use a dedicated Twitter account to share Schedule information and event details so that the website looks cleaner compared to just sharing the full timeline of the main ICT Game Jam account.             Posts have to be in reverse order (post the last information first) so it's easier to read on the website.

When the next year's event comes around, you'd have to delete all of the old tweets and tweet the new updated information.

**Comment by catcecilia** [comment]
I used my twitter as an example for my PR but it can easily be changed to a different account

**Comment by chrisl8** [comment]
Closing out old issues.
